# Generated by Django 4.1.2 on 2023-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='current_bpm',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mistakes',
            field=models.IntegerField(default=0),
        ),
    ]
