# Generated by Django 4.1.2 on 2023-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique_builder', '0003_remove_exercise_mistakes_exercise_completions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
