# Generated by Django 4.1.2 on 2022-12-10 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='measures',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='bpm',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='timesignature',
            name='beats',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timesignature',
            name='division',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16')], default=4),
        ),
    ]
