# Generated by Django 4.1.2 on 2022-12-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0002_alter_rate_measures_alter_tempo_bpm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempo',
            name='bpm',
            field=models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(10)]),
        ),
    ]
