# Generated by Django 4.1.2 on 2022-12-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metronome', '0004_alter_tempo_bpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Tempo',
        ),
    ]
